on:
  workflow_dispatch:
  push:
    tags:
      - '*'
# Environment variables available to all jobs and steps in this workflow
env:
  REGISTRY_NAME: HCacr001
  CLUSTER_NAME: hcaks001
  CLUSTER_RESOURCE_GROUP: Ruchi_RG
  NAMESPACE: dev
  SECRET: new
  APP_NAME: newapp
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.azcred }}'
        cluster-name: ${{ env.CLUSTER_NAME }}
        resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
