on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    steps:
      - name: az set context
      - uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.azcred }}'
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.RESOURCE_GROUP }}
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build image
        env:
         REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
        run: make build
      - name: Login to container registry
        env:
          SERVICE_PRINCIPAL_APP_ID: ${{ secrets.SERVICE_PRINCIPAL_APP_ID }}
          SERVICE_PRINCIPAL_SECRET: ${{ secrets.SERVICE_PRINCIPAL_SECRET }}
          SERVICE_PRINCIPAL_TENANT: ${{ secrets.SERVICE_PRINCIPAL_TENANT }}
          ACR_NAME: ${{ secrets.REGISTRY_USERNAME }}
          CLUSTER_NAME: hcaks001
          RESOURCE_GROUP: Ruchi_RG
          
        run: make registry-login
      - name: Push image
        env:
          ACR_NAME: ${{ secrets.REGISTRY_USERNAME }}
        run: make push
      - uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.azcred }}'
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.RESOURCE_GROUP }}
      - name: Get AKS credentials
        env:
          CLUSTER_RESOURCE_GROUP_NAME: ${{ secrets.CLUSTER_RESOURCE_GROUP_NAME }}
          CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
        run: |
          az aks get-credentials \
            --resource-group $CLUSTER_RESOURCE_GROUP_NAME \
            --name $CLUSTER_NAME \
            --overwrite-existing
      - name: Deploy application
        env:
          ACR_NAME: ${{ secrets.REGISTRY_USERNAME }}
        run: make deploy
